### ISSUE TITLE
Errors in Docker containers from text files checked out with Windows line endings

### ISSUE THREAD

**Issue by znmeb** [EMCain/pandaid-api#4]
If you're running Docker for Windows with a GitHub repository, text files that land in a container must have Unix line endings or you will get mysterious errors. The Git for Windows default is to check them out as text files. See https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings for the details.

**Comment by geophpherie** [comment]
@znmeb I pulled the most recent updates to master with your changes and still seeing line ending errors on my windows machine.

```bash
pandaid-api_web_1 exited with code 127
web_1            | Postgres is ready! ✨ 💅
web_1            | /usr/bin/env: ‘python\r’: No such file or directory
pandaid-api_web_1 exited with code 127
web_1            | Postgres is ready! ✨ 💅
web_1            | /usr/bin/env: ‘python\r’: No such file or directory
pandaid-api_web_1 exited with code 127
web_1            | Postgres is ready! ✨ 💅
web_1            | /usr/bin/env: ‘python\r’: No such file or directory
pandaid-api_web_1 exited with code 127
web_1            | Postgres is ready! ✨ 💅
web_1            | /usr/bin/env: ‘python\r’: No such file or directory
```


I will try deleting and re-cloning.

**Comment by geophpherie** [comment]
yah okay that seems to do it. So hopefully when we move the repo and everyone re-clones this shouldn't be a problem anymore!

**Comment by znmeb** [comment]
Tested on Windows 10 Pro / Docker for Windows and working. Closing!
