### ISSUE TITLE
Add Issue and Pull Request templates

### ISSUE THREAD

**Issue by bhgrant8** [EMCain/pandaid-api#9]
## Summary

Github allows for the use of templates for creating issues and Pull Requests. 
More on templates:
https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

As a project lead and developer I would like to add templates to this repo for our use.

### Basic behavior example

Example use of templates in Hack Oregon Project:

https://github.com/hackoregon/civic-devops/issues/new/choose

And another from Gatsby:

https://github.com/gatsbyjs/gatsby/tree/master/.github/ISSUE_TEMPLATE

### Motivation

Templates help to organize conversation, implement good development practices, and in prioritizing work.

**Comment by bhgrant8** [comment]
Adding for tracking -

Tasks:

Create 3 Issue templates:
- [ ] service request
- [ ] feature request
- [ ] documentation request

- [ ] Create Pull request template

Add related documentation
- [ ] contributing
- [ ] how to file issue

**Comment by maryannet** [comment]
Thank you this is very useful
